view_annotations: True # view BBs overlayed on image

occlusion_aware: True
visibility_thresh: 0.5
component_visibility_thresh: 0.1
min_pixels: 200

create_sky: True

plane_size: 200 # metres
min_obj_count: 20 # min number of objects in scene
max_obj_count: 30 # max number of objects in scene

min_camera_height: 15 # metres
max_camera_height: 35 # metres
min_camera_tilt: 86 # degrees
max_camera_tilt: 89 # degrees

min_sun_energy: 2 # W/m^2
max_sun_energy: 5 # W/m^2
max_sun_tilt: 90 # degrees

num_img: 1000 # number of images to render
